### ISSUE TITLE
Support deploying to mrm

### ISSUE THREAD

**Issue by rfscholte** [mojohaus/mrm#10]
When trying to deploy, the plugin fails with 

```
java.lang.UnsupportedOperationException
    at org.codehaus.mojo.mrm.api.BaseFileSystem.put(BaseFileSystem.java:117)
    at org.codehaus.mojo.mrm.servlet.FileSystemServlet.doPut(FileSystemServlet.java:329)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:730)
```

It would be very helpfull if this part of the lifecycle is supported with mrm too.

**Comment by stephenc** [comment]
Ideally I'd like to be able to capture all deploys in a file and then one could trigger a deploy of those to another repo: i.e. Poor-man's staging

**Comment by rfscholte** [comment]
With a *mock* repository manager I would simply be able to verify the uploaded files, nothing more. I don't see the need for staging with this simple setup.

**Comment by stephenc** [comment]
Well we need to keep track of all the files that were uploaded. Once you have that list, staging becomes trivial to implement (i.e. Just walk the list and install/deploy)

**Comment by khmarbaise** [comment]
An extension could simply record the files (maybe more ) and mrm can check that list against the uploaded files ?

**Comment by rfscholte** [comment]
@stephenc @khmarbaise Please review https://github.com/mojohaus/mrm/tree/MRM-10
Have a look at the `src/it/hostedrepo` at how the maven-deploy-plugin could be tested with mrm.

**Comment by stephenc** [comment]
Looks fine if you can get the tests to actually pass ;-)
