### ISSUE TITLE
Plugin depends on `plexus-container-default`, which is EOL

### ISSUE THREAD

**Issue by basil** [mojohaus/mrm#162]
### Reproduction steps

- Use Maven 3.9.2.
- Run `mvn clean verify` in a project that uses `mrm-maven-plugin`.

### Expected Results

No warning

### Actual Results

```
[WARNING]  * org.codehaus.mojo:mrm-maven-plugin:1.5.0
[…]
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
```

### Anything else?

See https://maven.apache.org/docs/3.9.2/release-notes.html#notable-new-features for the root cause.

**Comment by slawekjaranowski** [comment]
Fixed by #144
