### ISSUE TITLE
Upgrade Maven api to 3.2.5 - drop support for Maven 2.x

### ISSUE THREAD

**Issue by slawekjaranowski** [mojohaus/mrm#99]
To change - new way
 - resolving artifacts
 - resolving and manage repository meta-data
 - resolving archetypes

**Comment by ajarmoniuk** [comment]
I can do that.

**Comment by slawekjaranowski** [comment]
> I can do that.

Great - please try step by step

**Comment by slawekjaranowski** [comment]
`mrm-api` - module looks like internal API for plugin, it contains implementations and so on ...
I we can break it, we can release next major version after Maven 2.x api will be removed and will be clear

**Comment by ajarmoniuk** [comment]
So far, the plugin is small, but it's a bit more intertwined than Versions or Enforcer. So, for the time being I'm going for the big bang, later on I may introduce gradual changes when I have it more or less done.

**Comment by ajarmoniuk** [comment]
for stage 2: https://issues.apache.org/jira/browse/MNG-7548

**Comment by ajarmoniuk** [comment]
@slawekjaranowski do you know if maven-artifact-manager is also to be replaced? (it provides a DefaultRepositoryMetadataManager and can be an alternative to maven-compat)

**Comment by slachiewicz** [comment]
@ajarmoniuk what left here to do?

**Comment by ajarmoniuk** [comment]
Right. I have no idea why I stopped with this.

archetype-common needs to be bumped. 

Looking into it.

**Comment by cstamas** [comment]
While investigating regarding this issue (unrelatd to this plugin) https://issues.apache.org/jira/browse/MNG-7705 I arrived here and found this: https://github.com/mojohaus/mrm/blob/master/mrm-maven-plugin/src/main/java/org/codehaus/mojo/mrm/plugin/DefaultFactoryHelper.java#L9

This is what "true legacy" means: this plugin completely circumvents resolver, and locking... it aged as a good milk 😄
